apiVersion: v1
values:
  images:
    etcd: docker.io/bitnami/etcd:3.5.15
patches:
  values.yaml:
    image:
      repository: "{{ registryFrom .images.etcd }}/{{ repositoryFrom .images.etcd }}"
      tag: "{{ tagFrom .images.etcd }}"
