apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-etcd.name" . }}-headless
  labels:
    {{- include "k8s-etcd.labels" . | nindent 4 }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: client
      port: 2379
      targetPort: client
    - name: peer
      port: 2380
      targetPort: peer
  selector:
    {{- include "k8s-etcd.selectorLabels" . | nindent 4 }}